name: CI Pipeline

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installation de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Installation des dépendances
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Vérification des paquets installés (optionnel)
      - name: Check installed packages
        run: npm list --depth=0

      # Exécution des tests
      - name: Run Tests
        run: |
          npm run test || { echo 'Tests failed'; exit 1; }

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # Construction de l'image Docker
      - name: Build Docker image
        run: docker build -t bilanox/moride:latest .

      # Push de l'image sur Docker Hub
      - name: Push to Docker Hub
        run: docker push bilanox/moride:latest
